version: '3'

services:
  app:
    build: ./app 
    container_name: app
    links:
      - mysql
    ports:
      - "5000:80"

  mysql:
    build: ./mysql
    container_name: mysql
    ports:
      - "30000:3306"
    # environment:
      # MYSQL_ROOT_PASSWORD: root
    restart: always
    # volumes:
    #   - ./mysql:/docker-entrypoint-initdb.d:ro



